FROM ubuntu:20.04

# Interactive mode requires user-prompts during build.
RUN DEBIAN_FRONTEND='noninteractive' TZ='Europe/London' apt-get update && apt-get install --assume-yes \
	tzdata keyboard-configuration

# Packaging
RUN apt-get update && apt-get install --assume-yes \
    sudo

# Basic terminal use
RUN apt-get update && apt-get install --assume-yes \
	vim curl htop tldr tree apt-file locate # basic terminal use

# GUI
RUN apt-get update && apt-get install --assume-yes \
	firefox vlc xclip

# Development
RUN apt-get update && apt-get install --assume-yes \
	git tig meld docker docker-compose python3 python3-pip python3-venv jq bats

# For traceability, in situ testing
COPY ./* /docker/