#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function assert_command_output_includes() {
    command=$1
    expected_output_component=$2

    output=$($command)

    printf "'$expected_output_component' in '$command': "
    if [[ "$output" != *"$expected_output_component"* ]]; then
        printf "failed, actually '$output'\n"
        exit 1
    else
        printf 'passed\n'
    fi
}

assert_command_output_includes 'git --version' 'git version'
assert_command_output_includes 'firefox --version' 'Mozilla Firefox'
assert_command_output_includes 'docker --version' 'Docker version'
assert_command_output_includes 'docker-compose --version' 'docker-compose version'
