name: On Push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          mock_DISPLAY=:0.0 # no X11 in CI
          DISPLAY=$mock_DISPLAY \
            docker-compose --file docker/docker-compose.test.yml up
