name: On Push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          ./build
          mock_DISPLAY=:0.0 # no X11 on CI
          DISPLAY=$mock_DISPLAY ./test
